"""add_time_travel_settings

Revision ID: a9595b367710
Revises: c26960e60bda
Create Date: 2025-08-21 09:26:20.213272

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "a9595b367710"
down_revision = "c26960e60bda"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_travel_settings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("offset_seconds", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("set_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("time_travel_settings_organization_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_by_user_id"],
            ["users.id"],
            name=op.f("time_travel_settings_set_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("time_travel_settings_pkey")),
        sa.UniqueConstraint(
            "organization_id", name=op.f("time_travel_settings_organization_id_key")
        ),
    )
    op.create_index(
        op.f("ix_time_travel_settings_created_at"),
        "time_travel_settings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_travel_settings_deleted_at"),
        "time_travel_settings",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_travel_settings_expires_at"),
        "time_travel_settings",
        ["expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_time_travel_settings_expires_at"), table_name="time_travel_settings"
    )
    op.drop_index(
        op.f("ix_time_travel_settings_deleted_at"), table_name="time_travel_settings"
    )
    op.drop_index(
        op.f("ix_time_travel_settings_created_at"), table_name="time_travel_settings"
    )
    op.drop_table("time_travel_settings")
    # ### end Alembic commands ###
