"""time_travel_use_absolute_time

Revision ID: 7a51897c6e15
Revises: a9595b367710
Create Date: 2025-08-21 10:38:32.210422

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "7a51897c6e15"
down_revision = "a9595b367710"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # Add new column as nullable first
    op.add_column(
        "time_travel_settings",
        sa.Column("simulated_time", sa.TIMESTAMP(timezone=True), nullable=True),
    )

    # Migrate existing data: simulated_time = current_time + offset_seconds
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE time_travel_settings 
        SET simulated_time = NOW() + (offset_seconds || ' seconds')::interval
        WHERE simulated_time IS NULL
    """)
    )

    # Make column not nullable
    op.alter_column("time_travel_settings", "simulated_time", nullable=False)

    # Drop old column
    op.drop_column("time_travel_settings", "offset_seconds")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "time_travel_settings",
        sa.Column("offset_seconds", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("time_travel_settings", "simulated_time")
    # ### end Alembic commands ###
